name: LINODE

on:
  workflow_dispatch

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
    - name: Install the Linode CLI
      uses: linode/action-linode-cli@v1
      with:
        token: ${{ secrets.linode }}
    - name: list
      run: linode-cli linodes ls --json
